/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#ebeef1",
        "on-error-container": "#93000a",
        "primary-container": "#0066ff",
        "background": "#f7fafd",
        "on-secondary-fixed": "#001849",
        "on-background": "#181c1e",
        "surface-container-high": "#e5e8eb",
        "tertiary-fixed-dim": "#ffb59d",
        "surface-dim": "#d7dadd",
        "on-tertiary-fixed-variant": "#832600",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#390c00",
        "on-secondary-container": "#294487",
        "tertiary": "#a33200",
        "on-primary-fixed-variant": "#003fa4",
        "on-primary": "#ffffff",
        "surface-bright": "#f7fafd",
        "secondary": "#425ca0",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dae1ff",
        "on-primary-fixed": "#001849",
        "on-tertiary-container": "#fff6f4",
        "surface-tint": "#0054d6",
        "primary": "#0050cb",
        "inverse-on-surface": "#eef1f4",
        "on-surface": "#181c1e",
        "on-primary-container": "#f8f7ff",
        "secondary-fixed": "#dae1ff",
        "outline-variant": "#c2c6d8",
        "surface-variant": "#e0e3e6",
        "secondary-fixed-dim": "#b3c5ff",
        "surface-container-low": "#f1f4f7",
        "on-surface-variant": "#424656",
        "inverse-primary": "#b3c5ff",
        "inverse-surface": "#2d3133",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#b3c5ff",
        "tertiary-container": "#cc4204",
        "outline": "#727687",
        "tertiary-fixed": "#ffdbd0",
        "on-error": "#ffffff",
        "surface-container-highest": "#e0e3e6",
        "on-secondary-fixed-variant": "#284386",
        "on-secondary": "#ffffff",
        "surface": "#f7fafd",
        "on-tertiary": "#ffffff",
        "secondary-container": "#9bb4fe",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}

